#ifndef INPUT_H
#define INPUT_H

#include <stdint.h>

static const char* const input_data[] = {
    "cotrinnnuxhe rceper blak�ves crinn�xhe foumrote salr�z rblankixhnut meurixhe lovtangt pr�-imprimaedjes tinaedje rapairixhreu calk�s ad�rreu ertchoezixh�t",
    "acrotchaxhe adrohnxhe berdel�yreut z�nks remilr�nt b�zant group�t freyront cdj�zans dismintixhexhe m�tourn�s ers�rtixhront disg�rnixhroz eterroz rs�rtixhseu kischavanxhe princip�l�s rewal�ves racrolreut coschirer conoxhnut erboerler hatir�ns avancixhanxhe aparint�s schaessexhe kibatoz rgons ravancixhr�nt distindoz torl�yr�s aconcofst�nit espexhiroz ep�tant ramoennans nonantinmes loukey�s ataetchroz pl�strixhs emacral�",
    "asgur�s c�rront ewalpas crotroz copinr�nt debizas cotournass egol�yes amousr�ns qt�rd eployaxhe parait�s rimimbr�yes halcot�xhe ele gueuyive kifroxhant dejurant schaest�yront",
    "ertcherdj�ns recoulot�xhe aclimat�cion z�nass noerixh�nt frotreyes batnut sondjant amindez erbrotches ametr�z rayixheu pr�ze rinict�yrans rcwirreus tot�l abtinixhaxhe rilujhans ec�dr�yes h�gn�yreut estiernixhnut csemnut dischoirshexhe ridisp�rti disp�rdaedje erpintans cotoidrans abiz� cotaeyes sup�zreu ershofl�nt frexhixha divizass ado�cixhanxhe l�jheuse riglatixh�nt",
    "rtours pleutiaxhes ermet�s vexh�dr�s bawions implir�z erprustixhreu kimaxh�s mesbrudj� saizixhroz comprinde ripayr�z esprognive sup�z�t qctaey�s erpayreut rwalonijheye rcoridjant radjond�t tcherieuse r�ansl�z ri�uv�nhhe t�st�yroz viermouyr� sohaitas dimor�xhe sicrotr�nt ramwinrixh�z astocaxhes bagn�z",
    "restch�fas anoyremt raclairixhreut distocnuxhe p�nixh�xhe dburtinr�nt erpolixhaxhes djouw�s pere ruteniom erpintixhnut caytant rbrotcha espaitch�xhe waerglae�r�ns rifond�z kipet�nxhe abotn�yreut obtinou bribreut",
    "riss�rtit rfwait�s dtes tourmint�yr�s h erhaprans betorass tchamoss�xhe chtroumfr� rloucr�ns ablocront ratenis esperimint�l�s emilr�z plant�t raprepeynut rclapreu bizress aco�trumtint t�xhondijh�nt achalandaxhe sbrognt�ye abobin�nxhe margaya acsujheus divnan rondjreut schaeyeu eur�ye kinoxhr�nt falixhaxhe avirnuxhe noerixhexhe rcoridjive",
    "resplicr�ns cabouyr�nt z�ncr� fornel�ns rbenixhr� tinlete compress-rastrindow�s discandjive eclawr�nt anoeri",
    "rwiwalreus amont�yress coviertixhreu crokez riboerlaxhe ratindass ahontiss crapr�s aschin�t riglatixhantes taetvhl�ye maxhas ec�daedje ap�vrixhr�s ertournans rassombrir�z tourmint�yr�z s�rar�ot ritourner rdroetixhs concoista separront agolinas tchitchl�s rinoeri breyotr� ragrancixh�s br�yt�xhe aspitanxhe z�ncnut poitreu aprind�nt bol�ds ersitinn�ves araez�ves rip�rtixhront ramolir�z",
    "pormoennress pot� egadjr�ns sipoujhr�ns djonnlas oxhea acois�t imoudrixhaxhre ralantixhass crexhot�nt rabelixhr� semexhe uniformijhr�nt bagn�s tourmintexhe pormoennanxhe disgroxhi sicrirece abizreut pourixh�nxhe spitrea siketass noerireut cafrotress �jhey�s rst�raedje erdroetit raveurixhs h�rdaxhr�z t�telr�nt rst�rans adierceyrans stop�z",
    "covrans cracnut kipicaxhe rilivront respectaxhe vitras xhegn�t kidj�ze erschapreus sipitr�z golt�yreu rv�mir�ns blef�t souw�sxhe mared�nt rispite b�bes abossixhr�ns nourir�z amatiroz aspougn�ve renond�t sit�ve",
    "catchete pjexhi�z chica clicotress addjeurnut catuzexhe satur�s espelir�z apontians shofelreyes erpinteyress ritcherdjaxhe sgot�z",
    "bernatront saeyea disaeuras apixhr�z disrunixh�nxhe rpik�ye rasgurress brouyas rv�mixhr�ns croejhr�ns cdj�z�ye agritch�nt raprotch�nxhe djouwixhaxhes al�rdjixhaxhes rebolr�z rioclamanxhe frotr�ns sikepeyr� z�nca el�jhans rilopreu bonis",
    "royteas rotans racamuchy�z asbleuwiroz ragrandixhress abtinixhe kitchessanxhe glignant picans rilome ctap�t ber�dnut rigret�ve rsouwr� p�rt�t",
    "cs�ynut maxhront roumins pardonez hantr� eralreus hairut pansou aveulas afront�ns guinchnut drov�z cayst�yr�z apairixh�ns cribotreu siblarixheu zinzine disgroxhixhoz cviesnut creuzanxhe ado�cir�z espitro�lreu pesse craper coss�yrans abat�s sor�s schoyowe ewaer�yr�ns sitramelress drouctaxhe aburtacress assimblreut aviyixhante alonguixhress fornixh�t etablir� esbrogntanxhe abuz�xhe ch�maxhe",
    "claw�nt abrutireut erescoul�t crocroz domine raprotchive ripolixhass rascod�s coschavront rinagngnut lopass n�jhixh�t esblarroz nawes enondaxhe riwagans dispairixhe edjalass goviinr�ns retchesses baloujhe croxhe-noejhe erverdixheus sicrotreu enairixhoz savoz racamucheyront vleur resser�ve avolr�ns comand�xhe",
    "cotaeyr� rgroxhixhaxhe �rmonijh�s tcshesronlt rustelr�ns copilroz djinn�nt carwaitr�s trov�t disfroyive disbalr�ns rcarculans m�djes",
    "b�ya rafa�r�nt rmared�yress dilamintnut djaenir� abizr� h�rdea rascourtixh�t ercopyives ramidr�yr�nt p�ternicr�s z�nnut",
    "s�rt�s caracteristik�s rafleurixh�nxhe macs�d�ye avalreut imimbr�ve ofwoya bouter ersint�z adramt�yr�z rifroedireu co�tchey�s aviyir�s ercopiaxhe blam� discw�rl�ynut rflorir�ns prinj�s coraedje demission�ve sinonimes raezive rprezintr�z rescoulaxhes b�m�z esp�tant",
    "ridjouwnut hbitant acsegneyes consolreu estantchant discrapele rmplireut otorijhress francijhr�s schavass cdj�zxyes br�yexhe w�rmagnanxhe erp�rtixhas rmwaijhir�s traw�yes boureatr�nt difalir�nt a-eurant calcroz greco-latenes cober�lreu adviertixh�t viermouyreut ewalp� rwaitreut disofide grin afrikinnes esprognt�s neteyr�ns stronnress diliberaxhes",
    "replae�nut cdj�z�ves dr�yas amwinrixhnut aroedixhans cotchess�z rischape schavn�nxhe p�vuions pr�mete acondjeurreus cboutas escpepass ranairixhoxhe recw�rl�yront adroveu sitiernixha lev�s rn�jhixheus aprindnuxhe adjin�ass t�st�xhe rilur�s soladj�s zoumnuxhe ristramass disbobinaxhes scanr�s hagnr�z acwachfixhant kimaxh�s acoird�y�s shuv�nt cfroxhives forfroyr�nt",
    "stampreus cachaxhes p�nixho esclepes am�rtixhr�nt plairans sindjant sip�gnreut distchoezir�ns sitoc�de rissouwreut discovrass elivnut bouxhrans acomplixha afin�xhe kischoya bradnut rissayives",
    "clairixh�nxhe waerglaec�ns ragranciroz lh�dje plor�t groxhixha esp�rdoxhe comuncreu berotress tcherdjeuse not�xhe escreper",
    "erf�tchr�nt ercrouwixhr�z ec�der tuzin�xhe cerejhes sepass texhow�s atinrixhass obt�ns p�y�z foumass rvoeye pgxh�ves bastixhoz ranaireyr�z erlujhaxhe cloct�yes pardone calcreut ersaetch�nt xhules sop�xhe guindayr�ns dispolixhant coixhaxhe erpasses vizitaxhe radjondeu csegn�nxhe ridjaenireu chopr�s",
    "ridjouw�z adjond�t prest�xhe met�s ratinrir�nt blincnut bout pyib� rilomaedjes cloct�ve saiwress rispitass tournik�xhe efant rstram�nxhe blacant estamp�",
    "avolesr ridroetir�z ar�l�xhe mozint�ye rdjetreu dischavaxhe sicay�yes m� aval�yes aschinas apinses treye ctournanxhe boulonas disbobinress val�nxhe v�str�yr�nt neyass boerl�ynuxhe ddjunront zpleuteyront djouwixhr�ns on zohler trosses loc�le erveyaxhe mwaijhireu ergroxhixhnut spanixhroz spataxhes sitramt�s c�t�s brad�ves escusyive b�botexhe rsaizir� ashiow�s rmete raveurixhaxhe",
    "dinnress picants relijh�xhe rpl�strixhant schaess�nxhe metanxhe cimintas stramter adjondowes canadyin angueuz�nxhe",
    "peupl�y�s raguidroz libert�s anoezixh�s houtdin� coviertixhanxhe flatch racracolreu p�zrans blankixh�s recoulotass biyt�yroz tch�dreut s�vioneus g�rnixhreut rlom�nt produjhanxhe",
    "rip�rtixhexhe sibrognt�yrans noerixh�ns ripintixhreut dilapotnut sopoirtans h�rans provnant al�rdji XXII rnofrixha faflot�xhe cafrotreus schitr�nt ragrandixhoxhe napeas chinreu aspexhixh�xhe diszoumas m�dje sacrifiass brnixhrens abotn�t rwagz disraloyass neteyrans erglati riss�rtit sipotchant mok�t abuz�s pretchr�nt eplinnixhans kissem�ye p�rtixhexhe sbarront",
    "siblareyrans ascoxh�nxhe ric�zeu acertinreus sinyt ratienixhexhe rz-� emacral�t afilaxhe lindjes ber�axhe eraecin�s ricarculass arinnr�t atinrixha eberbwetront tchicotreu dispexhiss basgurnt rexhroz r�lroz boty�s disser�xhe ridroetixhr�z kifroyr�nt govienmints k�cfeye bay�nxhe ervoer�ns ramwinrixhass comelreu dlamintaxhe",
    "cmons t�xhonde hongrw�s trawront djonnl�ve sitampant frexh�s pourixhreu houmreut sibrognt�yreut esp�texhe ramwinrixhr�ns ramadjive ratcherixh�z erfl�wiress asbleuwixhe prind betchreut",
    "rast�rdjant aprest�nt et�r�s apocugnreu kitaeya ritroz egol�yr�z agayan amwinrixhr�s ashofler dimandreu rdobelreut tournez assouwr�s bizr�nt bastir�z erto�nront astotch�ns imprimaedjes cmandass aviyixhroz blamant broy�t pleut estope schavt�yress afolez",
    "comunik�ns erpougn�nxhe espelixhroz ridrov�nt coviersanxhe mozintans redj�rbaxhes tchedjr�s rtrov�s batas sicrandixhant demarress amlcvr� riss�rti rascr�w�ye peket bourloufreus ercopeyr�ns dir�nt atuzlass seurixhaxhes foutront escoursixhroz dilamintreu disflanir�z erlomaedjes",
    "wangn�t cmel�t carotr�nt disg�rnireu m�tournexhe rtinkeyr�nt pi�ant erdroetixhs erviknuxhe apougn�de riprindr�nt rtuzant segnrans londjinniveuzmint kipit�t g�rnixhaxhe situdeyroz racracolr�s afl�tchaxhe intr�yes lachexhe breyotm�xzhe ecinsanxhe m�jhinete redj�rbez ermwaijhixhoz eredjistr�yr� dec�d�ye levnuxhe abelixhr� refoircixhreut apelans cinsresseps setcheyes mintixhes",
    "accept�yr�ns cfroyans abagu�s espitro�lr�ns rp�rtixh�s plitchot�ve ramolixhs kidur�s notifianxhe dj�spin� lapt�ves",
    "pzedxhe erbenixha ernon�r�z kipicront crev�d�xhe tchanout�s afl�wixhes sicrirece crotrans estramla amoenn�s boutaxhes hin�nxhe dezonorreu sitronn�t blondes ercarcul�xhe rozn�s sitramas ermared�yes t�stez buskintress ataetchr�nt dijhant calk�s ctrinnas foircixhreu pit�t aidreut rester sttchaxhe",
    "oland�s rih�ynass ermerciy�nt souw�v rifuzanxhe dislodj�t plact�yes loumanxhe fordjetnut kip�rtiront disfa�r�s adjudicass astipr�z sipat�ve rclaper han�t sh�s ricandi�he bast�rd�ve costrureus coschavrans sititchanxhe rimwaijhixhass raspxhiront ersetchixh�nt rissayreu dec�d�ve bansl�ves ri�uvow�s sketress rastokez erdj�ze erprodujhanxhe rimagnront espitro�l�nt purade ans baloudaxhe c�r�t",
    "djonda silovinnes cloctnuxhe schaves rlomr�s ploz amidr�ns rproduront reflechirans accion disfindou erbrotchr�ns acsuvow�s ridobelr� distaribucion abaya raw�rdaxhe core avilirans raloucr� agrandixhr� badjawe raidr�yr�s coviesr� met�xhe reyussixhr�s pareuzrans",
    "dispiert�ns covierti ewalp�ns esclefreut estampa p�rl�yreu propozans distocnut raw�rd�s ermousnuxhe schap�y�s l�reces rsouwr�s restans inm�v�s blawt�yr�es rado�cixha laireus rmaredant dotr�s viemant rt�nreut crejhlanxhb schandixhreus priyront clab�dr�nt rapoirtans s�vas rf� kischoyant rfl�wixheut dislecsikes riscr�ts brozd�ve ercin�nxhe advinous dmandr�nt sip�gne riansl�yru",
    "disb�tchreu socialisse raspexhixhreut pixhreus madjike b�canpt verdir�z rabieslez ribastireus kipitreut sinteu sitatr�s narene spr�tch�ns soufrixhroz vizitas cir�ves rilopront chinn�nxhe",
    "acsujhaxhe berwetnut naweas idrodjinne zinglass b�zrans ersindj�nxhe ap�rtin�xhe houtdin�ves bastixhant lodjant espitureye eberwetaxhe",
    "vud�z adawyives elaxhreut so�n�yr�ns raprotchas soriy�t escusy�t ranairi aroediroz toumant pondynt�s lomr�z erglatixhaxhes",
    "r�l�nt ermwaijhir�s binddim�dje erfl�wixhreu trimpes plantnuxhe ddjun�xhe raprindoxhe ddjunroz amatixhr�ns it�lyinn�s vizitr�z stokelreu chitroumfete ber�d�t rexheut crabot rproduxhe xhova aprindeus forn�jhixhr� rivoer�s eh�yes erlidjeuse ritmaedhes disflanireus assuranxhe briknuxhe espieme ervoeya",
    "atirreut bossalez riss�rtixhrans g�yotr�s ramwinrixh�z ad�res escrixhes rimwaijhixh�nt ravik�t briboznuxhe clicotr�ns lixhetes kiber�lanxhe foirdj�t mel�nxhe ragrancixhaxhes kip�rtix�nt kinoxheu rsetchixhress ovreuse",
    "froxhr�ns rcopeyreu dec�dr�ns retroclass �ansl�t ouxhaixhes gueuyt�ve toss�nt cp�rtixhant ap�vrir� jerployaxhe baligand mozint�yreus apurdans veyeus p�liress sitok�t ribatans lan�xhe g�yotreus baloude balaxhes morexhe oiz�ns dispexhixhront rih�yn�yroz risrans espornaxhe cmone transixhnuxhe cole soladj�nt rapoirtaxhe erdoblexhe distribouwao",
    "disb�tchroz espelixh�xhe copet�xhe rtch�ds g�liote sibrogntass abuzaxhe didjunexhe semr�z uzr�z rtchoeziront montaedjes dismolixhress coirs produjhoz amwinrir�z",
    "blhaoas aparint�yr�ns erunit atienixheu risk�yront ermaredaxhe cwer�xhe Ronsard mouzlinaxhe rvindjreut cop�rtixh�s esp�rgnans reflechixhe �rdjintnut cal�d�xhe tchery�t espaitch�z clairixheus ridroetiress cwatr�-vintinme jpulovers erpougnreu",
    "rployreu dj�rirans kissemreas kifesr�nt eplinnixhrans cost�t netiass dismefiant plaijhaxhes berdelas ratuzas r�uv�nxhe vvr�z el�reu conseyrewt �ansl�s riw�rdaxhe raspexhixhass r�ty�xhe louk�ns ermerceyront mannest� adjixhante eberbwetreut nost djouw� oteurs cotrinn�ves ratinrirans rn�jhixhnuxhe atcht�yreu cafougnreus dimorront poennes soriront ramidr�nt cimintant riverdixhoz rifl�wir�nt ber�lass",
    "ridrovanxhe h�yn�yr�z plitcht�yr�z djoleye erv�mixhress acoirdans addjurnuxee arocreut moennans estramr� saynut rifroedixh�nt",
    "moloneure rmosterr�z cond�n� dislecsike rivindjront clawas erpl�strixh schit�s mannet�s �ansl�nt",
};

static const uint32_t INPUT_WORD_COUNTS[] = {
    15,
    40,
    19,
    36,
    30,
    20,
    34,
    10,
    37,
    33,
    23,
    13,
    23,
    15,
    40,
    31,
    13,
    12,
    26,
    33,
    35,
    19,
    12,
    31,
    17,
    40,
    11,
    17,
    36,
    32,
    18,
    27,
    26,
    35,
    11,
    31,
    39,
    27,
    39,
    19,
    13,
    13,
    30,
    20,
    35,
    16,
    22,
    40,
    12,
    10,
};

#define INPUT_LINE_COUNT 50

#endif
